- name: Manage Files
  hosts: all
  become: yes
  become_user: root  
  tasks:
  - name: Creating a file with content
    copy:
      dest: "/var/www/html/index.html"
      content: |
        hello world
